# Generated by Django 3.2.4 on 2021-08-20 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingPlanPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packageImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('packageName', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
