# Generated by Django 3.2.4 on 2021-08-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_weddingplanpackages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interestmodel',
            old_name='interest_height',
            new_name='interest_max_age',
        ),
        migrations.RenameField(
            model_name='interestmodel',
            old_name='interest_maxage',
            new_name='interest_max_height',
        ),
        migrations.RenameField(
            model_name='interestmodel',
            old_name='interest_minage',
            new_name='interest_min_age',
        ),
        migrations.AddField(
            model_name='interestmodel',
            name='interest_min_height',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
