# Generated by Django 3.2.4 on 2021-08-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_remove_interestmodel_interest_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddingplanpackages',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='weddingplanpackages',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weddingplanpackages',
            name='packageName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='weddingplanpackages',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
