# Generated by Django 3.2.4 on 2021-08-21 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_auto_20210821_2041'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeddingPlanPackages',
            new_name='WeddingPlanPackagesModel',
        ),
    ]
