# Generated by Django 3.2.4 on 2021-08-21 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_alter_weddingplanpackagesmodel_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeddingPlanPackagesModel',
        ),
    ]
