# Generated by Django 3.2.4 on 2021-08-23 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0017_wishlistmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistmodel',
            name='wished_profile',
        ),
        migrations.AddField(
            model_name='wishlistmodel',
            name='wished_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.profilemodel'),
        ),
    ]
