# Generated by Django 3.2.4 on 2021-08-23 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0018_auto_20210823_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistmodel',
            old_name='wished_user',
            new_name='wished_profile',
        ),
    ]
