# Generated by Django 3.2.4 on 2021-08-23 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0019_rename_wished_user_wishlistmodel_wished_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishListModel',
        ),
    ]
